### PR TITLE
Fix browser builds webpack

### PR DESCRIPTION
**Pull request by stchang**
to accompany https://github.com/vishesh/racketscript/pull/208/files, and fix https://github.com/vishesh/racketscript-playground/issues/17

these examples still not working:
- [x] pattern matching
- doesnt like the `document.write`: `Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.`
- [x] flappy birds: 
- doesn't show up in `run-area` for some reason
- [ ] overview:
- console warning: `DevTools failed to load source map: Could not load content for https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.18.2/addon/search/matchesonscrollbar.min.js.map: Load canceled due to load timeout`

### CODE REVIEW

**Comment by vishesh** [comment]
Sorry, pushed to your branch directly by mistake (Github's `gh pr checkout` apparently sets the upstream too). I had trouble running webserver without updating package[lock] file, so just updated that.

**Comment by stchang** [comment]
hah ok no problem

**Comment by stchang** [comment]
Not sure if my changes are the proper way to do things, but with my latest pr (https://github.com/vishesh/racketscript/pull/221), all the examples can be compiled and run properly, except for pattern match, which still doesnt like the `document.write`

**Comment by stchang** [comment]
Ok, now with these changes, and https://github.com/vishesh/racketscript/pull/221, all the playground examples compile and run properly for me without errors!  (1 warning from `overview` example)

here's a test server if you want to check: http://161.35.54.145:8080/

Now I'm going to switch to using your https://github.com/vishesh/racketscript/pull/222 instead.

**Comment by vishesh** [comment]
Should I merge this?

**Comment by stchang** [comment]
let me test that last commit

**Comment by stchang** [comment]
good to merge now

**Pull request merged**
